# ---------------------------------------------------------------------------- #
# Base Setup                                                                   #
# ---------------------------------------------------------------------------- #
stages:
  - test
  - package
  - release

before_script:
  - ./devops/pypi/setup_poetry.sh

cache:
  paths:
    - .cache/pypoetry

# ---------------------------------------------------------------------------- #
# Test                                                                         #
# ---------------------------------------------------------------------------- #
# test:development:py39:
#   stage: test
#   image: python:3.9
#   variables:
#     REPORT_COVERAGE: "false"
#     TOX_ENVS: "py39-djng42"
#   script:
#     - ./devops/pypi/a_pycqa_1_install_dependencies.sh
#     - ./devops/pypi/a_pycqa_2_execute_tests.sh
#     - ./devops/pypi/a_pycqa_3_upload_coverage.sh
#   cache:
#     key: ${CI_JOB_NAME}
#     paths:
#       - .tox
#   only:
#     - develop

# test:development:py310:
#   stage: test
#   image: python:3.10
#   variables:
#     REPORT_COVERAGE: "false"
#     TOX_ENVS: "py310-djng42,py310-djng50,py310-djng51"
#   script:
#     - ./devops/pypi/a_pycqa_1_install_dependencies.sh
#     - ./devops/pypi/a_pycqa_2_execute_tests.sh
#     - ./devops/pypi/a_pycqa_3_upload_coverage.sh
#   cache:
#     key: ${CI_JOB_NAME}
#     paths:
#       - .tox
#   only:
#     - develop

# test:development:py311:
#   stage: test
#   image: python:3.11
#   variables:
#     REPORT_COVERAGE: "false"
#     TOX_ENVS: "py311-djng42,py311-djng50,py311-djng51"
#   script:
#     - ./devops/pypi/a_pycqa_1_install_dependencies.sh
#     - ./devops/pypi/a_pycqa_2_execute_tests.sh
#     - ./devops/pypi/a_pycqa_3_upload_coverage.sh
#   cache:
#     key: ${CI_JOB_NAME}
#     paths:
#       - .tox
#   only:
#     - develop

# test:development:py312:
#   stage: test
#   image: python:3.12
#   variables:
#     REPORT_COVERAGE: "false"
#     TOX_ENVS: "py312-djng42,py312-djng50,py312-djng51"
#   script:
#     - ./devops/pypi/a_pycqa_1_install_dependencies.sh
#     - ./devops/pypi/a_pycqa_2_execute_tests.sh
#     - ./devops/pypi/a_pycqa_3_upload_coverage.sh
#   cache:
#     key: ${CI_JOB_NAME}
#     paths:
#       - .tox
#   only:
#     - develop

test:tag:py312:
  stage: test
  image: python:3.12
  variables:
    REPORT_COVERAGE: "false"
  script:
    - ./devops/pypi/a_pycqa_1_install_dependencies.sh
    - ./devops/pypi/a_pycqa_2_execute_tests.sh
    - ./devops/pypi/a_pycqa_3_upload_coverage.sh
  only:
    - /v(\d+)\.(\d+)\.(\d+)/

test:master:py312:
  stage: test
  image: python:3.12
  variables:
    REPORT_COVERAGE: "true"
    TOX_ENVS: "coverage"
  script:
    - ./devops/pypi/a_pycqa_1_install_dependencies.sh
    - ./devops/pypi/a_pycqa_2_execute_tests.sh
    - ./devops/pypi/a_pycqa_3_upload_coverage.sh
  only:
    - master

# ---------------------------------------------------------------------------- #
# Package                                                                      #
# ---------------------------------------------------------------------------- #
package:tag:py312:
  stage: package
  image: python:3.12
  script:
    - ./devops/pypi/b_package_1_build.sh
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  dependencies:
    - test:tag:py312
  only:
    - /v(\d+)\.(\d+)\.(\d+)/

# ---------------------------------------------------------------------------- #
# Release                                                                      #
# ---------------------------------------------------------------------------- #
release:tag:py312:
  stage: release
  image: python:3.12
  script:
    - ./devops/pypi/c_release_1_setup_credentials.sh
    - ./devops/pypi/c_release_2_publish.sh
  dependencies:
    - package:tag:py312
  only:
    - /v(\d+)\.(\d+)\.(\d+)/
