[tool.poetry]
name = "django-sb-simple-migraitons"
version = "0.1.0"
description = ""
authors = ["zodiacfireworks <martin.vuelta@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.4"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.7"
black = "^21.5b2"
codecov = "^2.1.11"
coverage = "^5.5"
flake8 = "^3.9.2"
flake8-black = "^0.2.1"
jupyterlab = "^3.0.16"
mypy = "^0.812"
pre-commit = "^2.13.0"
pydocstyle = "^6.1.1"
pylint = "^2.8.3"
pylint-django = "^2.4.4"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
pytest-vcr = "^1.0.2"
python-dotenv = "^0.17.1"
tox = "^3.23.1"
twine = "^3.4.1"

[tool.black]
target_version = ['py39']
include = '\.pyi?$'
exclude = '''
/(\.git/
  |\.eggs
  |\.hg
  |__pycache__
  |\.cache
  |\.ipynb_checkpoints
  |\.mypy_cache
  |\.pytest_cache
  |\.tox
  |\.venv
  |_build
  |buck-out
  |build
  |dist
  |legacy
  |example
)/
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
